import Head from "next/head";
import KitchenCards from "../components/KitchenCard/KitchenCard";
import styles from "../styles/Kitchen.module.css";

const Kitchen = () => {
  return (
    <div className={styles.kitchen}>
      <Head>
        <title>Kawaii Kitchen</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.grid}>
          <KitchenCards
            label="Pantry"
            path="/pantry"
            img="/pantry-leaf.png"
            altText="Pantry Icon"
            height={270}
            width={270}
          />

          <KitchenCards
            label="Refrigerator"
            path="/refrigerator"
            img="/refrigerator-snowflake.png"
            altText="Refrigerator Icon"
            height={270}
            width={270}
          />

          <KitchenCards
            label="Recipes"
            path="/recipes"
            img="/recipe.png"
            altText="Recipe Icon"
            height={270}
            width={270}
          />

          <KitchenCards
            label="Groceries"
            path="/groceries"
            img="/grocery-cart.png"
            altText="Grocery List Icon"
            height={270}
            width={270}
          />
        </div>
      </main>
    </div>
  );
};

export default Kitchen;
