import Head from "next/head";
import KitchenCards from "../components/KitchenCard/KitchenCard";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Kawaii Kitchen</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.grid}>
          <KitchenCards
            path="/pantry"
            img="/pantry-leaf.png"
            altText="Pantry Icon"
            height={270}
            width={270}
          />

          <KitchenCards
            path="/refrigerator"
            img="/refrigerator-snowflake.png"
            altText="Refrigerator Icon"
            height={270}
            width={270}
          />

          <KitchenCards
            path="/recipes"
            img="/cooking-recipe.png"
            altText="Recipe Icon"
            height={270}
            width={270}
          />

          <KitchenCards
            path="/groceries"
            img="/grocery-cart.png"
            altText="Grocery List Icon"
            height={270}
            width={270}
          />
        </div>
      </main>
    </div>
  );
}
